### ISSUE TITLE
Edge action breaking for me

### ISSUE THREAD

**Issue by husseinbob** [cypress-io/github-action#135]
I have actions set up for Chrome and FF testing successfully, however I'm having issues with Edge, with the following yaml:

```yml
name: E2E Tests (Edge Chromium)
on: [push]
jobs:
  cypress-run-Edge:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Cypress run
        uses: cypress-io/github-action@v1.16.1
        with:
          browser: edge
          build: yarn build
          start: yarn start:test
          wait-on: http://localhost:3000
```

Set up and Checkout work OK, but then at the "Cypress Run" step:

```
C:\windows\system32\tar.exe -cz --force-local -f D:/a/_temp/cf8a3d77-16ca-49e2-8d5c-2aa14fdc6559/cache.tgz -C C:/Users/runneradmin/.cache/yarn .
tar.exe: Option --force-local is not supported
Usage:
  List:    tar.exe -tf <archive-filename>
  Extract: tar.exe -xf <archive-filename>
  Create:  tar.exe -cf <archive-filename> [filenames...]
  Help:    tar.exe --help
##[warning]The process 'C:\windows\system32\tar.exe' failed with exit code 1
saving cache path C:\Users\runneradmin\.cache\Cypress
primary key cypress-win32-x64-3c29172b7c522853126c1a2ec777668932a3f66036f02ae383a5639b593988586c00c041b7f2e9e084f569de704b2b3bba15feb21df75c76e1e2077a0503fba9
C:\windows\system32\tar.exe -cz --force-local -f D:/a/_temp/281673c5-0cc4-4bdd-808c-1ea9d6e77b67/cache.tgz -C C:/Users/runneradmin/.cache/Cypress .
tar.exe: Option --force-local is not supported
Usage:
  List:    tar.exe -tf <archive-filename>
  Extract: tar.exe -xf <archive-filename>
  Create:  tar.exe -cf <archive-filename> [filenames...]
  Help:    tar.exe --help
##[warning]The process 'C:\windows\system32\tar.exe' failed with exit code 1
yarn build
Error: There was an error when attempting to execute the process 'yarn'. This may indicate the process failed to start. Error: spawn yarn ENOENT
    at ExecState._setResult (D:\a\_actions\cypress-io\github-action\v1.16.1\dist\index.js:891:25)
    at ExecState.CheckComplete (D:\a\_actions\cypress-io\github-action\v1.16.1\dist\index.js:877:18)
    at ChildProcess.<anonymous> (D:\a\_actions\cypress-io\github-action\v1.16.1\dist\index.js:764:27)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
##[error]There was an error when attempting to execute the process 'yarn'. This may indicate the process failed to start. Error: spawn yarn ENOENT
```

I tried swapping `yarn` for `npm` but get similar results (complaining that npm ins't starting).

Following from this, I'm also wondering, if it's worth setting up tests for different browsers, if they're all Chromium based, what kind of tested features should I expect to pass in one browser but not the other?

Thanks

**Comment by jennifer-shehane** [comment]
Does you setup work if you switch the browser to Chrome or switch the 'runs-on' to another OS? Just want to make sure we exclude it being a problem with the rest of the action.

**Comment by husseinbob** [comment]
I tried switching "Edge"  for "Chrome" and got the same results: 

```yaml
name: E2E Tests (Edge Chromium)
on: [push]
jobs:
  cypress-run-Edge:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Cypress run
        uses: cypress-io/github-action@v1.16.1
        with:
          browser: chrome
          build: yarn build
          start: yarn start:test
          wait-on: http://localhost:3000
```
```log
Run cypress-io/github-action@v1.16.1
restoring cache C:\Users\runneradmin\.cache\yarn
primary key yarn-win32-x64-e9c5e1f508d78e01f1931888e40f571a4faf57e3ad98e58b8ade63a03e9ced39e0c1e406524343ed934da6ae162e063d741f2f17ced4c2f2d0ac06de3c7a93bc
restoring cache C:\Users\runneradmin\.cache\Cypress
primary key cypress-win32-x64-e9c5e1f508d78e01f1931888e40f571a4faf57e3ad98e58b8ade63a03e9ced39e0c1e406524343ed934da6ae162e063d741f2f17ced4c2f2d0ac06de3c7a93bc
Cache not found for input keys: yarn-win32-x64-e9c5e1f508d78e01f1931888e40f571a4faf57e3ad98e58b8ade63a03e9ced39e0c1e406524343ed934da6ae162e063d741f2f17ced4c2f2d0ac06de3c7a93bc, yarn-win32-x64-e9c5e1f508d78e01f1931888e40f571a4faf57e3ad98e58b8ade63a03e9ced39e0c1e406524343ed934da6ae162e063d741f2f17ced4c2f2d0ac06de3c7a93bc.
Cache not found for input keys: cypress-win32-x64-e9c5e1f508d78e01f1931888e40f571a4faf57e3ad98e58b8ade63a03e9ced39e0c1e406524343ed934da6ae162e063d741f2f17ced4c2f2d0ac06de3c7a93bc, cypress-win32-x64-.
C:\windows\system32\cmd.exe /D /S /C "C:\npm\prefix\yarn.cmd --frozen-lockfile"
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning Pattern ["postcss-svgo@^4.0.2"] is trying to unpack in the same destination "C:\\Users\\runneradmin\\AppData\\Local\\Yarn\\Cache\\v6\\npm-postcss-value-parser-4.0.2-17b997bc711b333bab143aaed3b8d3d6e3d38258-integrity\\node_modules\\postcss-value-parser" as pattern ["postcss-value-parser@^4.0.0","postcss-value-parser@^4.0.2"]. This could result in non-deterministic behavior, skipping.
warning file-loader@2.0.0: Invalid bin field for "file-loader".
warning url-loader@1.1.2: Invalid bin field for "url-loader".
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "next-fonts > file-loader@2.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "next-fonts > url-loader@1.1.2" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
```

As for switching OS, are you aware of which other options should support edge? AFAIK, only `windows-latest` will do.

**Comment by husseinbob** [comment]
I have the FF and Chrome runners set up running on ubuntu just fine if that's what you mean.

**Comment by alberthaff** [comment]
I'm having the same issue.

The actions runs all my tests in Chrome & FF on ubuntu without any issues.

<details><summary>My action</summary>

```
name: Run e2e-tests
jobs:
  build: (...)
  e2e-chrome: (...)
  e2e-firefox: (...)
  e2e-edge:
    name: "Test: Microsoft Edge"
    runs-on: windows-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - name: Download build assets
        uses: actions/download-artifact@v1
        with:
          name: webapp-e2e
          path: dist
      - name: Start static-server
        run: |
          npm -g install github:alberthaff/static-server
          cd dist
          static-server -p 4200 -n index.html &
      - uses: cypress-io/github-action@v1
        with:
          browser: edge
          wait-on: "http://localhost:4200"
          env: runId=${{ github.run_number }}
```
</details>

**Comment by mrjdavidfg** [comment]
My tests were running well in windows-latest edge, but once that problem came out, when re-executing the workflows it worked again.

**Comment by nglinh** [comment]
I think this is due to cypress-io/github-action is using a forked version of action/cache.

On the main line, there's a patch that seems to fix the issue: https://github.com/actions/cache/pull/126/files

If cypress-io/github-action-cache cherrypicks this commit it should be fine.

**Comment by bahmutov** [comment]
Could you please use the latest v2 version of this action? We have switched to the official cache module, thus this problem should be solved.

**Comment by MikeMcC399** [comment]
@husseinbob 

This is an old issue and I'm just looking at Edge right now.  

The [example-edge](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-edge.yml) test on `windows-latest` is running fine here. The workflow log [3858929910](https://github.com/cypress-io/github-action/actions/runs/3858929910) shows success.

Is there any outstanding issue with Edge or can this be closed?

**Comment by MikeMcC399** [comment]
@ricardo-dematos 

> - Could this be related with #620 ?

- `github-action` was specifically updated to resolve this issue (#135), however for some reason the issue remained open. This issue is more than 2 years old. I suggested in https://github.com/cypress-io/github-action/issues/135#issuecomment-1374831765 that it should be closed.

- The example for Edge runs successfully with current versions. See https://github.com/cypress-io/github-action/actions/runs/5520698137.

```text
 │ Cypress:        12.17.1                                                                        │
 │ Browser:        Edge 114 (headless)                                                            │
 │ Node Version:   v16.16.0 (/home/runner/runners/2.305.0/externals/node16/bin/node)              │
 │ Specs:          1 found (spec.cy.js)                                                           │
 │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
```

- Are you able to reproduce this issue with Edge? Do you have some reason for linking this issue to #620? I could not see any connection between the two issues.

**Comment by nagash77** [comment]
@MikeMcC399 sorry I missed your comment but you are correct this issue should be closed at this point as resolved.  If folks are still seeing issues using edge please open a new issue with a reproducible example and we will be happy to take a look!  Going to close this issue at this time.
